### ISSUE TITLE
Multiprocessing error

### ISSUE THREAD

**Issue by Attila94** [qianguih/voxelnet#12]
The following error keeps appearing over and over again when I run the evaluation code on Windows 10 x64 with `python test.py -n pre_trained_car`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Attila\Projects\intelligent-vehicles\voxelnet\voxelnet\test.py", line 10, in <module>
    from model import RPN3D
  File "C:\Users\Attila\Projects\intelligent-vehicles\voxelnet\voxelnet\model\__init__.py", line 12, in <module>
    from model.model import *
  File "C:\Users\Attila\Projects\intelligent-vehicles\voxelnet\voxelnet\model\model.py", line 12, in <module>
    from utils import *
  File "C:\Users\Attila\Projects\intelligent-vehicles\voxelnet\voxelnet\utils\__init__.py", line 12, in <module>
    from utils.kitti_loader import *
  File "C:\Users\Attila\Projects\intelligent-vehicles\voxelnet\voxelnet\utils\kitti_loader.py", line 44, in <module>
    TRAIN_POOL = multiprocessing.Pool(4)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Attila\Anaconda2\envs\python364\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.


```

**Comment by ghost** [comment]
Did you manage to fix this? I'm having the same issue

**Comment by lonlonago** [comment]
only use one point cloud a time will solve this issue, do not use the mp

**Comment by gkadusumilli** [comment]
did anyone resolved multiprocessing run time error issue

**Comment by swzaaaaaaa** [comment]
> Did you manage to fix this? I'm having the same issue
Have you solved it？

**Comment by swzaaaaaaa** [comment]
> only use one point cloud a time will solve this issue, do not use the mp

Excuse me, where should I modify it?
