### ISSUE TITLE
python3 test.py crashes on pretrained model? Kindly help

### ISSUE THREAD

**Issue by chowkamlee81** [qianguih/voxelnet#31]
After executing python3 test.py crashes with erroe below

Traceback (most recent call last):
  File "/home/administrator/Documents.orig/Kumar_FileSystem/3D_Object_Detection/voxelnet-master/test.py", line 69, in <module>
    tags, results, front_images, bird_views, heatmaps = model.predict_step(sess, batch, summary=False, vis=True)
  File "/home/administrator/Documents.orig/Kumar_FileSystem/3D_Object_Detection/voxelnet-master/model/model.py", line 285, in predict_step
    probs, deltas = session.run(output_feed, input_feed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value MiddleAndRPN_/conv21/kernel
	 [[Node: MiddleAndRPN_/conv21/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](MiddleAndRPN_/conv21/kernel)]]
	 [[Node: concat_101/_449 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1999_concat_101", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'MiddleAndRPN_/conv21/kernel/read', defined at:
  File "/home/administrator/Documents.orig/Kumar_FileSystem/3D_Object_Detection/voxelnet-master/test.py", line 58, in <module>
    avail_gpus=cfg.GPU_AVAILABLE.split(',')
  File "/home/administrator/Documents.orig/Kumar_FileSystem/3D_Object_Detection/voxelnet-master/model/model.py", line 70, in __init__
    input=feature.outputs, alpha=self.alpha, beta=self.beta, training=self.is_train)
  File "/home/administrator/Documents.orig/Kumar_FileSystem/3D_Object_Detection/voxelnet-master/model/rpn.py", line 97, in __init__
    temp_conv, training=self.training, activation=False, bn=False, name='conv21')
  File "/home/administrator/Documents.orig/Kumar_FileSystem/3D_Object_Detection/voxelnet-master/model/rpn.py", line 142, in ConvMD
    temp_conv = tf.layers.conv2d(pad, Cout, k, strides=s, padding="valid", reuse=tf.AUTO_REUSE, name=scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/convolutional.py", line 621, in conv2d
    return layer.apply(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py", line 828, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py", line 699, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/convolutional.py", line 144, in build
    dtype=self.dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py", line 546, in add_variable
    partitioner=partitioner)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable.py", line 436, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 786, in _get_single_variable
    use_resource=use_resource)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 2220, in variable
    use_resource=use_resource)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 2210, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 2193, in default_variable_creator
    constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 397, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3187, in identity
    "Identity", input=input, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value MiddleAndRPN_/conv21/kernel
	 [[Node: MiddleAndRPN_/conv21/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](MiddleAndRPN_/conv21/kernel)]]
	 [[Node: concat_101/_449 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1999_concat_101", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Process finished with exit code 1

**Comment by Jugaris89** [comment]
hi

it is happening to me too. Did you solve it?

**Comment by sainisanjay** [comment]
@chowkamlee81 @qianguih @Jugaris89 I am also getting same error. did anybody solved???

**Comment by z393** [comment]
@chowkamlee81 @Jugaris89 @sainisanjay I have the same problem , did u solve it ? Thx !

**Comment by Yi-Shi94** [comment]
I had the same problem. My pre-trained model name for -n was wrong.  It never got the weight file.

**Comment by dave98lzx** [comment]
I had the same problem. But I tried a little further. First the problem is "[[Node: MiddleAndRPN_/conv21/kernel/read = IdentityT=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]", where I changed the name of the class `MiddleAndRPN` in rpn.py into `MiddleAndRPN_` which seems to be a match with the traceback, and it seemed to go further but still had similar problem: "Attempting to use uninitialized value MiddleAndRPN_/deconv2/moving_mean". How can I solve this?

**Comment by 12lvxiaofeng12** [comment]
显卡内存不够

**Comment by wayne1627** [comment]
> 显卡内存不够

你有试过吗，显存大了就能运行?

**Comment by wayne1627** [comment]
> FailedPreconditionError (see above for traceback): Attempting to use uninitialized value MiddleAndRPN_/conv21/kernel

试过了不是显存的问题
