### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.box_overlaps'

### ISSUE THREAD

**Issue by YluXbei** [qianguih/voxelnet#55]
When I run the code **python3 voxelnet_ros.py** on unbuntu18.04,I get the issue

Traceback (most recent call last):
  File "voxelnet_ros.py", line 17, in <module>
    from model import RPN3D
  File "../voxelnet/model/__init__.py", line 12, in <module>
    from model.model import *
  File "../voxelnet/model/model.py", line 11, in <module>
    from utils import *
  File "../vpoxelnet/utils/__init__.py", line 10, in <module>
    from utils.box_overlaps import *
ModuleNotFoundError: No module named 'utils.box_overlaps'

I think maybe because there are some problem on cython ? But I`m so vegetable that I cant figure out what happen,could someone help me to solve this issue,thx.

**Comment by YluXbei** [comment]
actually its do have some problem on cython that python cant import the extension filename .pyx,in order to solve this issue,we should add  
`import pyximport`
`pyximport.install()`
before  import the .pyx module we need.
