### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.box_overlaps'

### ISSUE THREAD

**Issue by Huizhaoaaaa** [qianguih/voxelnet#83]
When I run the train.py, the following error appears：
   Traceback (most recent call last):

  File "E:\voxelnet-master\train.py", line 14, in <module>
    from model import RPN3D

  File "E:\voxelnet-master\model\__init__.py", line 12, in <module>
    from model.model import *

  File "E:\voxelnet-master\model\model.py", line 12, in <module>
    from utils import *

  File "E:\voxelnet-master\utils\__init__.py", line 10, in <module>
    from utils.box_overlaps import *

ModuleNotFoundError: No module named 'utils.box_overlaps'
the utils folder contains "box_overlaps.c" and "box_overlaps.pyx"
![image](https://user-images.githubusercontent.com/51786646/84749725-ed80b800-afec-11ea-8bc0-99e75f231ec4.png)

**Comment by kasai2210** [comment]
This model isn't working correctly in Windows, try using Linux or WSL2.

**Comment by miaozujia** [comment]
i have the same question, there is box_overlaps.c instead of box_overlaps.py, what can i do?

**Comment by cui19981127** [comment]
You can add at the beginning of the code
import pyximport
pyximport.install()
