### ISSUE TITLE
Facing below issue while executing train.py.

### ISSUE THREAD

**Issue by arm235** [qianguih/voxelnet#96]
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Dataset lidar length: 5237
Dataset tag length: 5237
Dataset total length: 5237
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\hp\anaconda3\envs\voxelnet\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\ci\opencv_1512688052760\work\modules\imgproc\src\resize.cpp, line 3289
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\voxelnet\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\hp\anaconda3\envs\voxelnet\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hp\Documents\VoxelNet-tensorflow\utils\kitti_loader.py", line 237, in loader_worker_main
    self.fill_queue(batch_size)
  File "C:\Users\hp\Documents\VoxelNet-tensorflow\utils\kitti_loader.py", line 166, in fill_queue
    voxel[idx * single_batch_size:(idx + 1) * single_batch_size])
  File "C:\Users\hp\Documents\VoxelNet-tensorflow\utils\kitti_loader.py", line 269, in build_input
    feature = np.concatenate(feature_list)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
![image](https://user-images.githubusercontent.com/56991912/142749217-f20945be-8c2f-4a4d-add6-6242961d870d.png)

**Comment by zkopcilova** [comment]
I'm facing the same issue
